Update "feature policy" refs to new name "permissions policy" (#1473)
w3c/webauthn pull request #1476
Opened 2020-08-29 02:40 UTC by jcayzac

Before
------

```
LINK ERROR: No 'idl' refs found for 'userVerification' with for='['PublicKeyCredentialCreationOptions']'.
{{PublicKeyCredentialCreationOptions/userVerification}}
✔  Successfully generated, with 1 linking errors
```

After
-----

```
LINK ERROR: No 'idl' refs found for 'userVerification' with for='['PublicKeyCredentialCreationOptions']'.
{{PublicKeyCredentialCreationOptions/userVerification}}
WARNING: No 'sctn-feature-policy' ID found, skipping MDN features that would target it.
✔  Successfully generated, with 1 linking errors
```

The extra warning comes from a reference to the old anchor in the `mdn/webauth` cache, it's not due to any change in this spec:

https://github.com/tabatkins/bikeshed-data/blob/e142c0bd2c803105f927509f0cefc95dd132ed62/data/mdn/webauthn.json#L2065

2020-09-02 19:18 UTC, equalsJeffH requested changes
this PR is touching > 900 files and so something odd is going on here. we only need to update index.bs appropriately.  can chat 1:1 if u wish to figure it out...

2020-09-02 19:39 UTC, selfissued requested changes
This PR should not be merged as-is as it touches many many files unrelated to the intended change.  All the changes should be removed other than those to index.bs.

2020-09-03 01:27 UTC, jcayzac commented
Hi @equalsJeffH 
The PR contains two commits. The commit that touches the specs touches `index.bs` only of course. The required cache update touches all the bikeshed stuff, like similar commits updating the cache.

2020-09-03 01:29 UTC, jcayzac commented
@equalsJeffH GitHub allows you to filter on a single PR commit. Here's the commit that touches `index.bs`: [`f36f73d` (#1476)](https://github.com/w3c/webauthn/pull/1476/commits/f36f73d5884cd5f7505c04bf769ebbb8fe2704a0)

2020-09-03 01:30 UTC, jcayzac commented
> This PR should not be merged as-is as it touches many many files unrelated to the intended change. All the changes should be removed other than those to index.bs.

Without the cache update the change should not be merged, as they will be link errors.

2020-09-03 01:31 UTC, jcayzac commented
Should I send a separate PR just for the first commit? I'm a bit confused. I'm used to work with projects that request PRs to be "atomic", i.e. self-contained.

2020-09-03 16:49 UTC, equalsJeffH commented
> I'm a bit confused. I'm used to work with projects that request PRs to be "atomic", i.e. self-contained.

Apologies, I was rushing when originally looking at this and did not understand the implications nor contents of the two separate commits. 

You are perhaps a more sophisticated git & github user than we are.  We have been updating the bikeshed cache infrequently and typically in separate commits that do only such an update.

> Should I send a separate PR just for the first commit? 

Yes, I think it'd be best to have two separate PRs.

Did you create  3693e38 using the directions here: https://github.com/w3c/webauthn#updating-copies-of-bikeshed-data-files-stored-in-this-repo ?

Do you have a bikeshed installation in `<local path to>/webauthn/bikeshed` ?

If so, perhaps you can also help out with issue #1477 ?

thanks

2020-09-07 04:18 UTC, jcayzac commented
> I think it'd be best to have two separate PRs.

Roger that, I'll send the first commit in a separate PR.

> Did you create [3693e38](https://github.com/w3c/webauthn/commit/3693e38aab39acdd009f2e61f32abd010f283fab) using the directions here: [w3c/webauthn#updating-copies-of-bikeshed-data-files-stored-in-this-repo](https://github.com/w3c/webauthn#updating-copies-of-bikeshed-data-files-stored-in-this-repo) ?

Yes, although I struggled a bit with these instructions at first. I'm glad to see it's not just me BTW!

> Do you have a bikeshed installation in `<local path to>/webauthn/bikeshed` ?

Yes.

> If so, perhaps you can also help out with issue #1477 ?

Sure!

2020-09-10 06:23 UTC, jcayzac commented
@equalsJeffH thanks for merging the cache update. I rebased this PR so it now only has the spec change.

2020-09-16 18:58 UTC, equalsJeffH approved these changes
LGTM, thx @jcayzac !

2020-09-16 19:08 UTC, jcjones approved these changes

2020-09-16 19:09 UTC, merged