Sections for client extensions and authenticator extensions
w3c/webauthn pull request #1762
Opened 2022-07-06 01:08 UTC by Firstyear

Fixes #1760

2022-07-06 01:09 UTC, Firstyear commented
I've linked my w3c account now.

2022-07-06 13:56 UTC, emlun requested changes
Thanks! This looks good to me apart from some minor polish suggestions.

2022-07-06 13:56 UTC, emlun commented on index.bs
>  IANA "WebAuthn Extension Identifiers" registry [[!IANA-WebAuthn-Registries]] established by [[!RFC8809]].
Please amend the line above this (6025) to:

```
This section and its subsections define an additional set of extensions to be registered in the
```

2022-07-06 13:56 UTC, emlun commented on index.bs
> +## Client Extensions
```suggestion
## Client Extensions

This section defines extensions that are only [=client extensions=].
```

2022-07-06 23:30 UTC, Firstyear commented
Thanks @emlun, I've applied your feedback :)

2022-07-07 09:47 UTC, emlun requested changes

2022-07-07 09:47 UTC, emlun commented on index.bs
> +This section and it's subsections defines an additional set of extensions to be registered in the
Typos:
```suggestion
This section and its subsections define an additional set of extensions to be registered in the
```

2022-07-07 09:47 UTC, emlun commented on index.bs
> +### FIDO <dfn>AppID</dfn> Extension (appid) ## {#sctn-appid-extension}
Ah right, you need to pad the header mark on both sides...
(this becomes very apparent in the [preview](https://pr-preview.s3.amazonaws.com/Firstyear/webauthn/pull/1762.html), which gets auto-added to the OP.)

```suggestion
### FIDO <dfn>AppID</dfn> Extension (appid) ### {#sctn-appid-extension}
```

2022-07-07 09:47 UTC, emlun commented on index.bs
> +### FIDO AppID Exclusion Extension (appidExclude) ## {#sctn-appid-exclude-extension}
```suggestion
### FIDO AppID Exclusion Extension (appidExclude) ### {#sctn-appid-exclude-extension}
```

2022-07-07 09:47 UTC, emlun commented on index.bs
> +### Credential Properties Extension (<dfn>credProps</dfn>) ## {#sctn-authenticator-credential-properties-extension}
```suggestion
### Credential Properties Extension (<dfn>credProps</dfn>) ### {#sctn-authenticator-credential-properties-extension}
```

2022-07-07 09:47 UTC, emlun commented on index.bs
> +### Large blob storage extension (<dfn>largeBlob</dfn>) ## {#sctn-large-blob-extension}
```suggestion
### Large blob storage extension (<dfn>largeBlob</dfn>) ### {#sctn-large-blob-extension}
```

2022-07-07 09:47 UTC, emlun commented on index.bs
> +### <dfn>User Verification Method</dfn> Extension (uvm) ## {#sctn-uvm-extension}
```suggestion
### <dfn>User Verification Method</dfn> Extension (uvm) ### {#sctn-uvm-extension}
```

2022-07-08 12:59 UTC, emlun commented on index.bs
>  IANA "WebAuthn Extension Identifiers" registry [[!IANA-WebAuthn-Registries]] established by [[!RFC8809]].
(The "defines" still needs to be updated to "define" here :slightly_smiling_face:)

2022-07-11 22:38 UTC, Firstyear commented
Sorry about that, fixed up :)

2022-07-13 23:27 UTC, merged