Fix inconsistencies in backup state flags
w3c/webauthn pull request #1772
Opened 2022-07-11 14:30 UTC by emlun

Fixes #1740. This depends on PR #1771.

I open this as a "draft" PR because it has PR #1771 as its base branch, to isolate the diff to the changes unique to this PR. I will re-target this PR to the main branch before merging.

2022-07-11 18:04 UTC, timcappalli commented on index.bs
> +                    - `1` means the [=public key credential source=] is is [=backup eligible=].
double "is"

2022-07-11 18:05 UTC, timcappalli requested changes
Outside of the extra "is" on line 3850, LGTM!

2022-07-11 18:12 UTC, emlun commented on index.bs
> +                    - `1` means the [=public key credential source=] is is [=backup eligible=].
Good catch, thanks!

2022-07-27 19:28 UTC, MasterKale approved these changes

2022-07-27 19:30 UTC, pascoej approved these changes
This looks good.

2022-08-10 14:24 UTC, akshayku approved these changes

2022-08-15 08:45 UTC, emlun commented
Thanks @timcappalli, but as noted in the top post I'll keep this as a "draft" PR until #1771 is merged.

2022-09-21 19:50 UTC, timcappalli approved these changes
lgtm

2022-09-21 19:54 UTC, merged