Adjust timeout for create and get operations
w3c/webauthn pull request #1885
Opened 2023-05-03 11:58 UTC by akshayku

Current timeout are very short in certain situations. 
Examples:
- Security keys: As these devices are external and depends on user behavior like locate/retrieve/use/put it back, often it leads to timeout of the operation and leads to bad user experience. 
- Phones: With Hybrid testing, while scanning QR codes, user has been found in similar situations as above described for security keys. 

Proposal:
Adjust timeout range to 5-10 mins. Default timeout: 5 mins.

2023-05-03 12:25 UTC, emlun requested changes

2023-05-03 12:25 UTC, emlun commented on index.bs
>              </dl>
The `switch` construct doesn't seem quite appropriate for this. I suggest replacing the `<dl>`s with the bulleted list syntax like below, around https://github.com/w3c/webauthn/pull/1885/files#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R1801-R1803 .

2023-05-03 12:25 UTC, emlun commented on index.bs
>                  </dl>
The `switch` construct doesn't seem quite appropriate for this. I suggest replacing the `<dl>`s with the bulleted list syntax like at https://github.com/w3c/webauthn/pull/1885/files#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R1801-R1803 .

2023-05-03 16:31 UTC, timcappalli approved these changes
lgtm

2023-05-03 19:56 UTC, agl approved these changes

2023-05-17 19:17 UTC, ve7jtb approved these changes
lgtm

2023-05-17 19:17 UTC, merged