remove passkey word
w3c/webauthn pull request #1938
Opened 2023-08-04 05:53 UTC by ko-koiwai

This PR removes the word "passkey"

See PR https://github.com/w3c/webauthn/pull/1936 for additional context.

+@maxhata

2023-08-04 14:44 UTC, timcappalli commented
The term is referenced by other methods and should not be removed.

I don't see any actual justification in this PR for its removal.

2023-08-04 15:05 UTC, timcappalli requested changes
This PR should be abandoned as the term is referenced by other methods and should not be removed. There are also other changes in this PR that are not called out, which is a bit misleading.

I don't see any actual justification in this PR for its removal. The justification for it being added in the first place is in the PR that was merged to add it and remains true. This seems to be more of a political move than constructive one.

2023-08-05 01:24 UTC, maxhata commented
There is a big confusion about what "passkeys" mean in the ecosystem.
The definition in the current spec adds another confusion. 
As an RP who are deploying FIDO technologies, this definition is troubling for messaging to consumers.

2023-08-05 02:39 UTC, timcappalli commented
@maxhata consumer messaging is not in scope for this web platform API.

2023-08-05 06:48 UTC, Firstyear commented
> @maxhata consumer messaging is not in scope for this web platform API.

Then why is "passkey" which is a consumer term contained within this standard? We already had a perfectly good terminology for discoverable keys.

2023-08-05 13:28 UTC, timcappalli commented
passkey is a noun, like password. Please see the original PR.

2023-08-06 02:54 UTC, Firstyear commented
> passkey is a noun, like password. Please see the original PR.

Being a noun doesn't prevent it being a noun associated with consumer messaging, nor that the noun is confusing.

2023-08-07 02:22 UTC, ko-koiwai commented
As per advices, I'll hold this PR and raise a new issue.

2023-08-09 14:06 UTC, ko-koiwai commented
Closing as Issue https://github.com/w3c/webauthn/issues/1939 was closed.

2023-08-09 14:06 UTC, closed without merging