Make the default value for the attestation member in assertion options be null
w3c/webauthn pull request #1972
Opened 2023-09-22 09:39 UTC by Kieun

The default value of attestation options in **assertion** was `none` and the intension was that the relying party does not want any attestation at assertion time.  In this case, the user agent and authenticator does not return any `attestationObject` which is backward compatible.
But, for `none` attestation options in **attestation** **does** always return attestation statement including `none` attestation statement or any other attestation statement with `self` attestation.

Now, with this PR, the default of attestation options in **assertion** is `null`.
So, if the RP does not set attestation option member value, the user agent now handles that value as `null`. In this case, the user agent does not request any attestation to the authenticator and it does not return attestationObject as a assertion response.
In other cases, if the RP explicitly sets attestation options including `none`, the user agent now sends such request like the way of attestation processing, and if any authenticator supports such requests, the authenticator may return attestation in assertions. Then, the user agent handles such response from the authenticator with additional steps such as replacing some potentially identifiable information.

Fixes #1941

2023-09-29 22:17 UTC, agl requested changes
For assertion-time attestation, specifying the formats as `["none"]` to the authenticator tells it [not to return](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#authenticatorGetAssertion) an attestation.

2023-09-30 00:49 UTC, Kieun commented
> For assertion-time attestation, specifying the formats as `["none"]` to the authenticator tells it [not to return](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#authenticatorGetAssertion) an attestation.

Indeed. While digging CTAP 2.2, I found that make credential operation also handles attestation format as well. 
@agl as far as I understand, there was no such option so that authenticator always returns the attestation for create operation. Such modification is intentional? @dwaite , @ve7jtb 

Due to such modification, the WebAuthn L3 also sends attestationFormats as ["none"] to the authenticator if the attestation options is `none`.  I think this also needs to reconsider since only CTAP 2.2+ can handle attestationFormats for create.

2023-10-05 07:23 UTC, Kieun commented
> For assertion-time attestation, specifying the formats as `["none"]` to the authenticator tells it [not to return](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#authenticatorGetAssertion) an attestation.

@agl I've addressed your suggestion in the following commit: a763f96fa3bf0906846e7f384eff9c2cda9cc428

2023-10-11 18:44 UTC, emlun requested changes
Why does `attestation: null` need to be distinct from `attestation: "none"`? It is already the case that the authenticator will not return an attestation statement if `attestation: "none"` ([step 13 of `authenticatorGetAssertion`](https://w3c.github.io/webauthn/#ref-for-attestation-object%E2%91%A0%E2%91%A1)), and if the authenticator does not return an attestation statement, the client will in turn set `AuthenticatorAssertionResponse.attestationObject` to null ([success branch of step 20 in `navigator.credentials.get()`](https://w3c.github.io/webauthn/#assertioncreationdata-assertionattestation)).

In #1941 you note:
>2. Set `attestation` as `none`: meaning is that I don't have any interests to verify the attestation, but if the authenticator could return `self` attestation (self-signed), it would be better than nothing.

But I don't think this is accurate. Self attestation should not be returned for `attestation: "none"` per the references above.

2023-12-14 01:13 UTC, MasterKale commented
From WG meeting @ 12/13: This is made moot by https://github.com/w3c/webauthn/pull/1997

2024-01-10 20:26 UTC, MasterKale commented
From WG meeting @ Jan 10: We've merged #1997 so this is no longer needed.

2024-01-10 20:26 UTC, closed without merging