Reference CTAP 2.1 errata spec
w3c/webauthn pull request #2004
Opened 2023-11-30 02:19 UTC by selfissued

Fixes #1635

2023-11-30 11:44 UTC, emlun requested changes

2023-11-30 11:44 UTC, emlun commented on index.bs
> +    "date": "June 21, 2021"
```suggestion
    "date": "June 21, 2022"
```

2023-12-05 11:57 UTC, emlun approved these changes
LGTM!

2023-12-05 14:36 UTC, ve7jtb approved these changes
LGTM

2023-12-11 19:24 UTC, timcappalli approved these changes

2023-12-13 20:09 UTC, MasterKale approved these changes

2023-12-13 20:09 UTC, agl approved these changes

2023-12-13 20:09 UTC, nadalin approved these changes

2023-12-13 20:10 UTC, dturnerx approved these changes
LGTM

2023-12-20 19:11 UTC, merged