Update Use Cases for L3
w3c/webauthn pull request #2139
Opened 2024-09-06 16:19 UTC by timcappalli

Closes #1720 #1735

This updates the use case section to align to ecosystem changes and new features in Level 3.

> [!NOTE]
> This is a draft / work in progress and is **not ready for formal review.**

2024-12-19 23:34 UTC, selfissued commented on index.bs
> +    * The user connects their USB security key
```suggestion
    * The user connects their USB security key.
```

2024-12-19 23:35 UTC, selfissued approved these changes

2025-01-15 13:09 UTC, emlun requested changes

2025-01-15 13:09 UTC, emlun commented on index.bs
> +### Workforce and Single-Device Credentials ### {#sctn-usecase-workforce-sdc}
"And" here makes me want to read this to mean the two use cases "Workforce" and "Single-Device Credentials". In that case the section contents then seem to imply that single-device credentials can _only_ be used by an employer mailing a pre-registered security key. I think using "with" instead makes it harder to misinterpret this in that way (and then the next section points out that other users can also use security keys and single-device credentials).

```suggestion
### Workforce with Single-Device Credentials ### {#sctn-usecase-workforce-sdc}
```

2025-01-15 13:09 UTC, emlun commented on index.bs
> +### Consumers and Multi-Device Credentials ### {#sctn-usecase-consumer-mdc}
Related to my other comment, let's use "with" here too for consistency and to not imply that multi-device credentials are only for consumers and consumers can only use multi-device credentials.

Also, since the example flows refer to a single "user", let's use the singular in the title too.

```suggestion
### Consumer with Multi-Device Credentials ### {#sctn-usecase-consumer-mdc}
```

2025-01-15 15:08 UTC, timcappalli commented on index.bs
> +    * The browser or operating system informs the user that they must change their PIN and prompts for a new one.
I think that would apply to many things here including client PIN entry in general, using CDA, etc, right? It is meant to be a high level ecosystem narrative, not directly referencing WebAuthn features.

2025-01-15 16:03 UTC, emlun commented on index.bs
> +    * The browser or operating system informs the user that they must change their PIN and prompts for a new one.
Fair point! So maybe a brief disclaimer is enough then, if anything. For example, appending something like "Note that details and feature availability may differ between client and authenticator implementations" to the introductory paragraph in §1.2? Or just not bother?

2025-01-15 17:19 UTC, timcappalli commented on index.bs
> +    * The browser or operating system informs the user that they must change their PIN and prompts for a new one.
how's this? 06cffbd033d3d4d2f6255b32910bb9ce433cc568

2025-01-15 17:30 UTC, emlun commented on index.bs
> +    * The browser or operating system informs the user that they must change their PIN and prompts for a new one.
Looks good, thanks!

2025-01-15 18:12 UTC, akshayku approved these changes

2025-01-16 21:00 UTC, timcappalli commented on index.bs
> +### Consumers and Multi-Device Credentials ### {#sctn-usecase-consumer-mdc}
a little lighter than workforce, but it's something: https://github.com/w3c/webauthn/pull/2139/commits/0ac2e40c71c3e8dbb691f40d0f18ffeee0efdae7

2025-01-17 00:06 UTC, MasterKale approved these changes
I'm approving because I think it's fine as-is. But might we want to include any L3-specific use cases that highlight new things like conditional create or any of the signals?

2025-01-17 11:45 UTC, emlun commented on index.bs
> +### Consumers and Multi-Device Credentials ### {#sctn-usecase-consumer-mdc}
:+1:

2025-01-17 11:45 UTC, emlun approved these changes

2025-01-22 20:08 UTC, merged